### ISSUE TITLE
Add support to show full description

### ISSUE THREAD

**Issue by mjohnson518** [adgsm/co2-storage#5]
We need to add support to show the full description of the Wallet Addresses, CIDs, Template Names and Base Template Names on the Assets, Templates, and Dashboard pages.

<img width="1351" alt="Screen Shot 2022-08-24 at 18 47 16" src="https://user-images.githubusercontent.com/44822571/186537240-53d74ec0-ce8f-4181-91b2-97f585172f5a.png">

**Comment by adgsm** [comment]
This is partially solved with commit 4267f033db8046b1ede342b41cd627dc83d1a4e3 (added copy to clipboard functionality)

**Comment by adgsm** [comment]
Do you have any idea what else / how we should show full descriptions?

**Comment by adgsm** [comment]
![Image](https://user-images.githubusercontent.com/5786211/187235011-26a3e06f-8f7c-49fa-9356-65716a885989.png)

**Comment by mjohnson518** [comment]
What I envision is functionality that shows the full name, description, or CID when you hover over the item. 

Right now, the template names/descriptions & CIDs get cut off and you have no way of seeing the full text.

Does that make sense? And can we implement that feature?

**Comment by adgsm** [comment]
Hover on desktop is OK. What about mobile? Click / Tap is reserved to navigate you to desired template, asset, etc.

**Comment by adgsm** [comment]
Solved with commit 043aa674bc128500b02f47d948fab0cc5dffe1fc
