### ISSUE TITLE
Add Toucan Schema

### ISSUE THREAD

**Issue by mjohnson518** [adgsm/co2-storage#6]
We need to add Toucans schema, as specified in their [Project Explorer Data Points doc](https://docs.google.com/spreadsheets/d/1737eCLU90syLRBgHoo895_zYyh21P5cbQTbRE7WynPc/edit?usp=sharing).

**Comment by mjohnson518** [comment]
Added. [Commit here](https://github.com/adgsm/co2-storage/commit/6f2f7f982c845cef77917aac2976fa811ca2c728).

**Comment by mjohnson518** [comment]
@adgsm can you review?

**Comment by adgsm** [comment]
Looks good!
